export const mockRoadmaps = [
  {
    id: "1",
    title: "ServiceNow Fundamentals",
    slug: "fundamentals",
    description: "Foundation Knowledge of the Now Platform.",
    difficulty: "Beginner",
    estimatedDuration: "2 Weeks",
    certification: "CSA Prerequisite",
    prerequisites: "None",
    careerOutcome: "Platform Associate",
    salaryRange: "$60k - $80k",
    phase: 1,
    unlocks: ["Administration", "Development", "ITSM Module"],
    learningObjectives: "Understand core ServiceNow architecture, navigate the UI confidently, and manage basic records and users.",
    color: "from-blue-600 to-blue-900",
    iconName: "BookOpen",
    order: 1,
    modules: [
      { id: "1-1", title: "Platform Introduction", description: "Architecture, instances, and basic concepts.", estimatedTime: "2h", completed: true },
      { id: "1-2", title: "Navigation & User Interface", description: "Next Experience UI, banners, and app navigator.", estimatedTime: "1h", completed: true },
      { id: "1-3", title: "Lists, Forms, Filters", description: "Navigating records and creating complex filters.", estimatedTime: "2h", completed: false },
      { id: "1-4", title: "Users, Groups, Roles", description: "Basic user administration and access.", estimatedTime: "2h", completed: false },
      { id: "1-5", title: "Tables & Records", description: "Dictionary, schema, and extending tables.", estimatedTime: "3h", completed: false },
      { id: "1-6", title: "Service Catalog", description: "Requesting items and catalog basics.", estimatedTime: "2h", completed: false },
      { id: "1-7", title: "Knowledge Base", description: "Creating and managing knowledge articles.", estimatedTime: "1h", completed: false },
      { id: "1-8", title: "Incident Management", description: "Basic incident lifecycle and resolution.", estimatedTime: "2h", completed: false },
    ]
  },
  {
    id: "3",
    title: "Administration",
    slug: "administration",
    description: "System administration and configuration.",
    difficulty: "Intermediate",
    estimatedDuration: "4 Weeks",
    certification: "CSA",
    prerequisites: "Fundamentals",
    careerOutcome: "ServiceNow Administrator",
    salaryRange: "$70k - $95k",
    phase: 2,
    unlocks: ["Security & Governance", "Workflow & Automation"],
    learningObjectives: "Configure UI, secure data with ACLs, and migrate changes between instances.",
    color: "from-amber-600 to-amber-900",
    iconName: "Settings",
    order: 2,
    modules: [
      { id: "3-1", title: "User & Role Management", description: "Advanced access control and delegation.", estimatedTime: "2h", completed: false },
      { id: "3-2", title: "ACLs", description: "Access Control Lists and security rules.", estimatedTime: "4h", completed: false },
      { id: "3-3", title: "Notifications", description: "Triggering events and notifications.", estimatedTime: "2h", completed: false },
      { id: "3-4", title: "Email Configuration", description: "Inbound actions and email templates.", estimatedTime: "3h", completed: false },
      { id: "3-5", title: "Import Sets", description: "Loading data via transform maps.", estimatedTime: "3h", completed: false },
      { id: "3-6", title: "Data Sources", description: "Connecting external data sets.", estimatedTime: "2h", completed: false },
      { id: "3-7", title: "Update Sets", description: "Capturing and moving configuration changes.", estimatedTime: "2h", completed: false },
      { id: "3-8", title: "System Properties", description: "Managing global instance properties.", estimatedTime: "1h", completed: false },
      { id: "3-9", title: "Scheduled Jobs", description: "Automating background tasks.", estimatedTime: "2h", completed: false },
    ]
  },
  {
    id: "4",
    title: "ServiceNow Development",
    slug: "development",
    description: "Core scripting and platform development.",
    difficulty: "Intermediate",
    estimatedDuration: "5 Weeks",
    certification: "CAD Prerequisite",
    prerequisites: "Fundamentals",
    careerOutcome: "ServiceNow Developer",
    salaryRange: "$90k - $130k",
    phase: 2,
    unlocks: ["Integrations", "Advanced Development"],
    learningObjectives: "Write client-side and server-side scripts to automate logic and customize the UI.",
    color: "from-rose-600 to-rose-900",
    iconName: "Code",
    order: 3,
    modules: [
      { id: "4-1", title: "Client Scripts", description: "OnLoad, onChange, and onSubmit scripts.", estimatedTime: "3h", completed: false },
      { id: "4-2", title: "Business Rules", description: "Before, After, Async, and Display rules.", estimatedTime: "4h", completed: false },
      { id: "4-3", title: "UI Policies", description: "No-code dynamic form behaviors.", estimatedTime: "2h", completed: false },
      { id: "4-4", title: "UI Actions", description: "Custom buttons and context menus.", estimatedTime: "2h", completed: false },
      { id: "4-5", title: "Script Includes", description: "Reusable server-side script libraries.", estimatedTime: "4h", completed: false },
      { id: "4-6", title: "GlideRecord", description: "Querying and manipulating database records.", estimatedTime: "4h", completed: false },
      { id: "4-7", title: "Scheduled Jobs", description: "Scripting recurring tasks.", estimatedTime: "2h", completed: false },
      { id: "4-8", title: "Fix Scripts", description: "Running one-time data correction scripts.", estimatedTime: "2h", completed: false },
    ]
  },
  {
    id: "2",
    title: "ITSM Module",
    slug: "itsm",
    description: "Master the IT Service Management applications.",
    difficulty: "Intermediate",
    estimatedDuration: "3 Weeks",
    certification: "CIS-ITSM Prerequisite",
    prerequisites: "Administration",
    careerOutcome: "ITSM Specialist",
    salaryRange: "$85k - $120k",
    phase: 3,
    unlocks: ["CMDB & Discovery"],
    learningObjectives: "Manage IT processes including Incidents, Problems, Changes, and Service Requests.",
    color: "from-emerald-600 to-emerald-900",
    iconName: "LifeBuoy",
    order: 4,
    modules: [
      { id: "2-1", title: "Incident Management", description: "End-to-end incident resolution workflow.", estimatedTime: "3h", completed: false },
      { id: "2-2", title: "Problem Management", description: "Root cause analysis and known errors.", estimatedTime: "3h", completed: false },
      { id: "2-3", title: "Change Management", description: "Standard, Normal, and Emergency changes.", estimatedTime: "4h", completed: false },
      { id: "2-4", title: "Request Management", description: "Service catalogs, order guides, and workflows.", estimatedTime: "3h", completed: false },
      { id: "2-5", title: "CMDB Basics", description: "Introduction to Configuration Items.", estimatedTime: "2h", completed: false },
      { id: "2-6", title: "Asset Management", description: "Hardware and software asset tracking.", estimatedTime: "2h", completed: false },
    ]
  },
  {
    id: "5",
    title: "Workflow & Automation",
    slug: "workflow-automation",
    description: "Process automation using modern tools.",
    difficulty: "Intermediate",
    estimatedDuration: "3 Weeks",
    certification: "Micro-Certification - Flow Designer",
    prerequisites: "Development",
    careerOutcome: "Process Automation Specialist",
    salaryRange: "$95k - $125k",
    phase: 3,
    unlocks: [],
    learningObjectives: "Design and orchestrate automated business processes without writing heavy code.",
    color: "from-purple-600 to-purple-900",
    iconName: "Workflow",
    order: 5,
    modules: [
      { id: "5-1", title: "Flow Designer", description: "Building no-code business flows.", estimatedTime: "4h", completed: false },
      { id: "5-2", title: "Integration Hub", description: "Connecting flows to third-party APIs.", estimatedTime: "3h", completed: false },
      { id: "5-3", title: "Workflow Editor", description: "Legacy workflow design and maintenance.", estimatedTime: "3h", completed: false },
      { id: "5-4", title: "Approvals", description: "Multi-level approval mechanisms.", estimatedTime: "2h", completed: false },
      { id: "5-5", title: "Automated Tasks", description: "Generating catalog tasks dynamically.", estimatedTime: "2h", completed: false },
      { id: "5-6", title: "SLA Management", description: "Service Level Agreements definitions.", estimatedTime: "2h", completed: false },
      { id: "5-7", title: "Escalations & Notifications", description: "Triggering alerts based on SLA breaches.", estimatedTime: "2h", completed: false },
    ]
  },
  {
    id: "6",
    title: "CMDB & Discovery",
    slug: "cmdb-discovery",
    description: "IT Operations Management foundation.",
    difficulty: "Advanced",
    estimatedDuration: "4 Weeks",
    certification: "CIS Discovery",
    prerequisites: "ITSM Module",
    careerOutcome: "ITOM Specialist",
    salaryRange: "$100k - $140k",
    phase: 3,
    unlocks: [],
    learningObjectives: "Architect a healthy CMDB and automate infrastructure population via Discovery.",
    color: "from-cyan-600 to-cyan-900",
    iconName: "Database",
    order: 6,
    modules: [
      { id: "6-1", title: "CMDB Design", description: "Class hierarchy and architecture.", estimatedTime: "3h", completed: false },
      { id: "6-2", title: "CI Relationships", description: "Mapping dependencies between items.", estimatedTime: "2h", completed: false },
      { id: "6-3", title: "Discovery", description: "Horizontal discovery phases and schedules.", estimatedTime: "5h", completed: false },
      { id: "6-4", title: "Service Mapping", description: "Top-down application service mapping.", estimatedTime: "4h", completed: false },
      { id: "6-5", title: "MID Server", description: "Installation, configuration, and capabilities.", estimatedTime: "2h", completed: false },
      { id: "6-6", title: "Reconciliation Rules", description: "Preventing data overlap and prioritizing sources.", estimatedTime: "3h", completed: false },
      { id: "6-7", title: "Identification & Sensors", description: "IRE processing and custom probes/sensors.", estimatedTime: "4h", completed: false },
    ]
  },
  {
    id: "7",
    title: "Integrations",
    slug: "integrations",
    description: "Connect ServiceNow to external enterprise systems.",
    difficulty: "Advanced",
    estimatedDuration: "4 Weeks",
    certification: "Micro-Certification - IntegrationHub",
    prerequisites: "ServiceNow Development",
    careerOutcome: "Integration Developer",
    salaryRange: "$100k - $145k",
    phase: 3,
    unlocks: [],
    learningObjectives: "Build robust inbound and outbound integrations using REST, SOAP, and standard protocols.",
    color: "from-pink-600 to-pink-900",
    iconName: "Globe",
    order: 7,
    modules: [
      { id: "7-1", title: "REST API", description: "Scripted REST APIs and REST Messages.", estimatedTime: "4h", completed: false },
      { id: "7-2", title: "SOAP API", description: "WSDL generation and SOAP envelopes.", estimatedTime: "2h", completed: false },
      { id: "7-3", title: "LDAP Integration", description: "Active Directory user and group imports.", estimatedTime: "3h", completed: false },
      { id: "7-4", title: "Azure AD Integration", description: "SSO and automated user provisioning.", estimatedTime: "3h", completed: false },
      { id: "7-5", title: "SCCM Integration", description: "Importing hardware data from Microsoft SCCM.", estimatedTime: "2h", completed: false },
      { id: "7-6", title: "Monitoring Tool Integrations", description: "SolarWinds, Dynatrace, Datadog webhooks.", estimatedTime: "3h", completed: false },
      { id: "7-7", title: "Event Management", description: "Event rules, alert correlation, and remediation.", estimatedTime: "4h", completed: false },
    ]
  },
  {
    id: "8",
    title: "Advanced Development",
    slug: "advanced-development",
    description: "Build rich custom applications and Service Portals.",
    difficulty: "Expert",
    estimatedDuration: "6 Weeks",
    certification: "CAD",
    prerequisites: "ServiceNow Development",
    careerOutcome: "Senior ServiceNow Engineer",
    salaryRange: "$120k - $160k",
    phase: 4,
    unlocks: ["Certification Path"],
    learningObjectives: "Master scoped application development, portal design, and advanced scripting.",
    color: "from-indigo-600 to-indigo-900",
    iconName: "Layers",
    order: 8,
    modules: [
      { id: "8-1", title: "Service Portal", description: "Pages, themes, and portal architecture.", estimatedTime: "4h", completed: false },
      { id: "8-2", title: "Catalog Item Development", description: "Advanced variables and client scripts.", estimatedTime: "3h", completed: false },
      { id: "8-3", title: "Record Producers", description: "Creating records from catalog submissions.", estimatedTime: "2h", completed: false },
      { id: "8-4", title: "Widgets", description: "AngularJS, HTML, CSS, and Server scripts.", estimatedTime: "6h", completed: false },
      { id: "8-5", title: "Scripted REST APIs", description: "Designing custom endpoints for external apps.", estimatedTime: "4h", completed: false },
      { id: "8-6", title: "Scoped Applications", description: "Delegated development and scope protection.", estimatedTime: "4h", completed: false },
      { id: "8-7", title: "Application Menus", description: "Building custom navigation experiences.", estimatedTime: "1h", completed: false },
      { id: "8-8", title: "Custom Tables & Modules", description: "Architecting relational database structures.", estimatedTime: "3h", completed: false },
    ]
  },
  {
    id: "9",
    title: "Security & Governance",
    slug: "security-governance",
    description: "Secure the platform and maintain compliance.",
    difficulty: "Expert",
    estimatedDuration: "3 Weeks",
    certification: "Security Operations",
    prerequisites: "Administration",
    careerOutcome: "GRC / SecOps Specialist",
    salaryRange: "$110k - $145k",
    phase: 4,
    unlocks: [],
    learningObjectives: "Implement robust data security, domain separation, and platform governance strategies.",
    color: "from-slate-600 to-slate-900",
    iconName: "Shield",
    order: 9,
    modules: [
      { id: "9-1", title: "ACLs", description: "Advanced scripted Access Control Lists.", estimatedTime: "3h", completed: false },
      { id: "9-2", title: "Data Security", description: "Encryption contexts and Edge Encryption.", estimatedTime: "3h", completed: false },
      { id: "9-3", title: "Domain Separation", description: "MSP architecture and data segregation.", estimatedTime: "4h", completed: false },
      { id: "9-4", title: "Audit & Compliance", description: "System logs, history sets, and auditing.", estimatedTime: "2h", completed: false },
      { id: "9-5", title: "Instance Security", description: "Hardening and Security Center dashboards.", estimatedTime: "2h", completed: false },
      { id: "9-6", title: "Security Best Practices", description: "Defending against XSS and injection.", estimatedTime: "2h", completed: false },
      { id: "9-7", title: "Roles & Permissions Strategy", description: "Designing scalable RBAC models.", estimatedTime: "3h", completed: false },
    ]
  },
  {
    id: "10",
    title: "Certification Path",
    slug: "certification-path",
    description: "Achieve official ServiceNow certifications.",
    difficulty: "Expert",
    estimatedDuration: "Self-Paced",
    certification: "All Mainline Certifications",
    prerequisites: "Advanced Development",
    careerOutcome: "ServiceNow Architect",
    salaryRange: "$150k - $220k+",
    phase: 5,
    unlocks: [],
    learningObjectives: "Prepare for, schedule, and pass the mainline ServiceNow certification exams.",
    color: "from-yellow-600 to-yellow-900",
    iconName: "Award",
    order: 10,
    modules: [
      { id: "10-1", title: "CSA", description: "Certified System Administrator.", estimatedTime: "Exam Prep", completed: false },
      { id: "10-2", title: "CAD", description: "Certified Application Developer.", estimatedTime: "Exam Prep", completed: false },
      { id: "10-3", title: "CIS", description: "Certified Implementation Specialist (ITSM, Discovery, etc.).", estimatedTime: "Exam Prep", completed: false },
      { id: "10-4", title: "Advanced Certifications", description: "CMA, CTA, and specialized micro-certifications.", estimatedTime: "Exam Prep", completed: false },
    ]
  }
];
